import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div>
      <Head>
        <title>h3lped | discord dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favico.ico" />
      </Head>


    </div>
  )
}
