import Main from '../components/Main'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import About from '../components/About'
import Skills from '../components/Skills'


export default function Home() {
  return (
    <div>
      <Head>
        <title>h3lped | 13 yr old developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favico.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />

    </div>
  )
}
